<a href="https://colab.research.google.com/github/minyeoong/python-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list_data=[1,2,3]

In [ ]:
print(list_data)

[1, 2, 3]


In [ ]:
import numpy as np

In [ ]:
array = np.array(list_data)

In [ ]:
print(array)

[1 2 3]


In [ ]:
print(array.size)

3


In [ ]:
print(array.dtype)

int64


In [ ]:
#0부터 3까지의 배열 만들기, arange함수

In [ ]:
array1 = np.arange(4)

In [ ]:
print(array1)

[0 1 2 3]


In [ ]:
array2 = np.zeros((4,4),dtype=float) #zeros함수 (0으로 초기화)

In [ ]:
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
array3 = np.ones((3,3),dtype=float)

In [ ]:
print(array3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#0부터 9까지 랜덤하게 초기화된 배열 만들기
array4 = np.random.randint(0,10,(3,3))#0부터 9까지 랜덤한 숫자 3*3matrix

In [ ]:
print(array4)

[[7 7 1]
 [5 5 0]
 [4 5 6]]


In [ ]:
#평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열(표준정규분포)
array5 =np.random.normal(0,1,(3,3))

In [ ]:
print(array5)

[[-0.34058201 -0.06040634  0.232898  ]
 [ 0.92523048  0.86620371 -0.01724461]
 [-0.43332256  2.12710064 -0.84630427]]


Numpy 배열합치기

In [ ]:
array1 = np.array([1,2,3])

In [ ]:
array2 =np.array([4,5,6])

In [ ]:
array3 = np.concatenate([array1,array2])

In [ ]:
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


Numpy 배열 형태 바꾸기

In [ ]:
#reshape함수
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))

In [ ]:
print(array2)

[[1 2]
 [3 4]]


In [ ]:
array1 =np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
print(array2)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
array3 =np.concatenate([array1,array2],axis=0)
print(array3)

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


Numpy 배열 나누기

In [ ]:
array = np.arange(8).reshape(2,4)

In [ ]:
left,right = np.split(array,[2],axis=1)#array를 인덱스2 기준, 열 기준 split

In [ ]:
print(left)

[[0 1]
 [4 5]]


In [ ]:
print(right)

[[2 3]
 [6 7]]


Numpy의 연산과 함수

In [ ]:
#Numpy 상수 연산
array = np.random.randint(1,10,size=4).reshape(2,2)

In [ ]:
print(array)

[[7 5]
 [9 6]]


In [ ]:
mul_array = array*10
print(result_array)

[[70 50]
 [90 60]]


In [ ]:
plus_array = array+2
print(plus_array)

[[ 9  7]
 [11  8]]


In [ ]:
array1 = np.arange(4).reshape(2,2) #2x2
array2 = np.arange(2) #1x2
#브로드캐스트: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환
array3 = array1 +array2 
print(array3)

[[0 2]
 [2 4]]


In [ ]:
array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1,array2],axis=0)
array4 = np.arange(0,4).reshape(4,1)

print(array3+array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [ ]:
array1 = np.arange(16).reshape(4,4)
print(array1)
array2 = array1<10 #마스킹 연산
print(array2) 
array1[array2]=100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


Numpy의 집계 함수

In [ ]:
array = np.arange(16).reshape(4,4)
print("최대값: ",np.max(array))
print("최소값: ",np.min(array))
print("합계: ",np.sum(array))
print("평균값: ",np.mean(array))


최대값:  15
최소값:  0
합계:  120
평균값:  7.5


In [ ]:
print("합계: ",np.sum(array,axis=0))

합계:  [24 28 32 36]


In [ ]:
print("합계: ",np.sum(array,axis=1))

합계:  [ 6 22 38 54]
