<a href="https://colab.research.google.com/github/minyeoong/Python-Data-Analysis-and-Image-Processing/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy의 활용

In [3]:
import numpy as np
# 단일 객체 저장 및 불러오기
array = np.arange(0,10)
np.save('saved.npy',array)

In [4]:
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#복수 객체 저장 및 불러오기
array1 = np.arange(0,10)
array2 = np.arange(10,20)
np.savez('saved.npz',array1 =array1,array2=array2)
data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']

In [6]:
print(result1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(result2)

[10 11 12 13 14 15 16 17 18 19]


Numpy 원소의 정렬

In [8]:
#오름차순 정렬
array = np.array([5,9,10,3,1])
print(array)

[ 5  9 10  3  1]


In [11]:
array.sort()

In [12]:
print(array)

[ 1  3  5  9 10]


In [13]:
#내림차순
print(array[::-1])

[10  9  5  3  1]


In [15]:
#각 열을 기준으로 정렬
array = np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]


In [16]:
array.sort(axis=0)

In [17]:
print(array)

[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [19]:
#균일한 간격으로 데이터 생성
array= np.linspace(0,10,5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
#난수의 재연(실행마다 결과 동일)
print(np.random.randint(0,10,(2,3)))

[[6 4 4]
 [1 5 5]]


In [24]:
array1 = np.arange(0,10)

In [25]:
array2 = array1
array2[0]=99

In [26]:
print(array1)

[99  1  2  3  4  5  6  7  8  9]


In [27]:
#Numpy에서는 array1와 array2가 동일한 주소를 가리키므로 array2를
#바꾸면 array1 또한 바뀌게 된다.

In [29]:
array1 =np.arange(0,10)
array2 = array1.copy()
array2[0]=99
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
#array1.copy()를 이용하면 동일한 주소를 가리키지 않는다.

In [31]:
#중복된 원소 제거
array = np.array([1,1,2,2,2,3,3,4])
print(np.unique(array))

[1 2 3 4]
