<a href="https://colab.research.google.com/github/minyeoong/Python-Data-Analysis-and-Image-Processing/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy의 활용

In [1]:
import numpy as np
# 단일 객체 저장 및 불러오기
array = np.arange(0,10)
np.save('saved.npy',array)

In [2]:
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#복수 객체 저장 및 불러오기
array1 = np.arange(0,10)
array2 = np.arange(10,20)
np.savez('saved.npz',array1 =array1,array2=array2)
data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']

In [4]:
print(result1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
print(result2)

[10 11 12 13 14 15 16 17 18 19]


Numpy 원소의 정렬

In [6]:
#오름차순 정렬
array = np.array([5,9,10,3,1])
print(array)

[ 5  9 10  3  1]
